import {useEffect,useState} from "react";import {api} from "../services/api.js";
const TYPES=["Breakfast","Lunch","Snack","Dinner"];
export default function Nutrition(){const[foods,setFoods]=useState([]),[day,setDay]=useState(null),[e,setE]=useState(""),[m,setM]=useState({type:"Lunch",name:"Chapati",qty:8}),[hint,setHint]=useState(null),[note,setNote]=useState(""),[scan,setScan]=useState(null),[menu,setMenu]=useState(null),[busy,setBusy]=useState("");
  const load=()=>Promise.all([api.get("/nutrition/foods"),api.get("/nutrition/today"),api.get("/menus/latest")]).then(([f,d,mn])=>{setFoods(f);setDay(d);setMenu(mn)}).catch(x=>setE(x.message));useEffect(()=>{load()},[]);
  const run=async(label,fn)=>{setE("");setBusy(label);try{await fn()}catch(x){setE(x.message)}setBusy("")};
  const log=()=>{setNote("");return run("Saving…",async()=>{const r=await api.post("/nutrition/meals",{type:m.type,items:[{name:m.name,qty:+m.qty}]});const i=r.items[0];setNote(`Added ${i.qty} × ${i.name}: ${Math.round(i.kcal)} kcal, ${Math.round(i.protein)}g protein, ${Math.round(i.carbs)}g carbs, ${Math.round(i.fat)}g fat`);await load()})};
  const look=async()=>{try{const f=await api.get("/nutrition/resolve?name="+encodeURIComponent(m.name));setHint(f)}catch{setHint(null)}};
  const analyse=file=>run("Analysing your meal…",async()=>{const fd=new FormData();fd.append("image",file);const r=await api.post("/ai/analyze-meal",fd);setScan({type:"Lunch",photoUrl:r.photoUrl,foods:r.foods})});
  const confirm=()=>run("Saving…",async()=>{await api.post("/nutrition/meals",{type:scan.type,source:"ai",photoUrl:scan.photoUrl||undefined,items:scan.foods.map(f=>({name:f.name,qty:+f.quantity,unit:f.unit,kcal:f.calories,protein:f.protein,carbs:f.carbs,fat:f.fat,fiber:f.fiber}))});setScan(null);await load()});
  const edit=(i,k,v)=>setScan({...scan,foods:scan.foods.map((f,j)=>j==i?{...f,[k]:v}:f)});
  const readMenu=file=>run("Reading your hostel menu…",async()=>{const fd=new FormData();fd.append("image",file);const r=await api.post("/ai/analyze-menu",fd);await api.post("/menus",{forDate:r.date||new Date().toISOString().slice(0,10),imageUrl:r.imageUrl||undefined,meals:r.meals});await load()});
  const tot=scan&&scan.foods.reduce((t,f)=>({k:t.k+ +f.calories,p:t.p+ +f.protein}),{k:0,p:0});
  return <><h1>Nutrition</h1>{e&&<p className="err" role="alert">{e}</p>}{busy&&<p className="mu" role="status">{busy}</p>}
  {day&&<div className="grid"><div className="card"><div className="mu">Today</div><div className="big">{Math.round(day.totals.kcal)} kcal</div><div className="mu">{Math.round(day.totals.protein)}g protein · {Math.round(day.totals.carbs)}g carbs · {Math.round(day.totals.fat)}g fat</div></div></div>}
  <div className="card"><h3>Log food</h3><div className="row"><select aria-label="Meal" value={m.type} onChange={x=>setM({...m,type:x.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select>
    <input list="foods" aria-label="Food" value={m.name} onChange={x=>{setM({...m,name:x.target.value});setHint(null)}} onBlur={look}/><datalist id="foods">{foods.map(f=><option key={f.id} value={f.name}/>)}</datalist>
    <input type="number" min="0.25" step="any" aria-label="Quantity" style={{width:90}} value={m.qty} onChange={x=>setM({...m,qty:x.target.value})}/>{hint&&<span className="mu">{hint.unit==="pc"?"pieces":hint.unit}</span>}<button className="pri" onClick={log}>Add</button></div>{hint&&<p className="mu">{hint.name}: {Math.round(hint.kcal)} kcal, {hint.protein}g protein per {hint.unit==="g"||hint.unit==="ml"?"100 "+hint.unit:hint.unit}</p>}{note&&<p className="ok" role="status">{note}</p>}<p className="mu">Plurals and local names work (chapatis, rotis, dahi). Any quantity works.</p></div>
  <div className="card"><h3>Scan my meal</h3><input type="file" accept="image/*" capture="environment" aria-label="Meal photo" onChange={x=>x.target.files[0]&&analyse(x.target.files[0])}/>
    {scan&&<><p className="mu">Estimated nutrition. Review and correct before saving.</p>{scan.foods.map((f,i)=><div className="row" key={i}><input value={f.name} aria-label="Food" onChange={x=>edit(i,"name",x.target.value)}/><input type="number" step="any" style={{width:80}} aria-label="Quantity" value={f.quantity} onChange={x=>edit(i,"quantity",x.target.value)}/><input type="number" style={{width:80}} aria-label="Calories" value={f.calories} onChange={x=>edit(i,"calories",x.target.value)}/><span className="mu">kcal · {Math.round(f.confidence*100)}% sure</span><button className="sec" onClick={()=>setScan({...scan,foods:scan.foods.filter((_,j)=>j!=i)})}>Remove</button></div>)}
    <p><b>~{Math.round(tot.k)} kcal · ~{Math.round(tot.p)} g protein</b></p><div className="row"><select aria-label="Meal" value={scan.type} onChange={x=>setScan({...scan,type:x.target.value})}>{TYPES.map(t=><option key={t}>{t}</option>)}</select><button className="pri" disabled={!scan.foods.length} onClick={confirm}>Confirm and save</button><button className="sec" onClick={()=>setScan(null)}>Discard</button></div></>}</div>
  <div className="card"><h3>Hostel menu</h3><input type="file" accept="image/*" aria-label="Menu photo" onChange={x=>x.target.files[0]&&readMenu(x.target.files[0])}/>
    {menu?<>{TYPES.map(t=>{const it=menu.items.filter(i=>i.mealType===t);return it.length?<div className="row" key={t}><b>{t}</b><span className="mu">{it.map(i=>i.name).join(", ")}</span></div>:null})}</>:<p className="mu">Your hostel menu isn't uploaded yet.</p>}</div>
  <div className="card"><h3>Food diary (today)</h3>{day&&day.meals.length?day.meals.map(x=><div className="row" key={x.id}><b>{x.type}</b><span>{x.items.map(i=>`${i.name} × ${i.qty}`).join(", ")}</span><span className="mu">{Math.round(x.items.reduce((s,i)=>s+i.kcal,0))} kcal · {Math.round(x.items.reduce((s,i)=>s+i.protein,0))}g P · {Math.round(x.items.reduce((s,i)=>s+i.carbs,0))}g C · {Math.round(x.items.reduce((s,i)=>s+i.fat,0))}g F</span><button className="sec" onClick={()=>run("Deleting…",async()=>{await api.del("/nutrition/meals/"+x.id);await load()})}>Delete</button></div>):<p className="mu">No meals logged yet.</p>}</div></>}
